### ISSUE TITLE
Share .idea project directory and dependencies

### ISSUE THREAD

**Issue by CrazyCoder** [pclewis/mcpatcher#27]
Could you please commit .idea project since you already share .iml files and also put all the dependencies in the lib folder of the project and share it as well for easier project building?

**Comment by prupe** [comment]
Project files are checked in for mcpatcher version 2.  You should have everything you need to build now.

**Comment by CrazyCoder** [comment]
Thank you!

**Comment by prupe** [comment]
I should also mention that you won't be able to run straight from the IDE.  Build the jar and run java -jar out/artifacts/mcpatcher/mcpatcher.jar instead.
