### ISSUE TITLE
MCPatcher.addOrReplaceFile - Messes up class file names

### ISSUE THREAD

**Issue by LexManos** [pclewis/mcpatcher#30]
You use classFile.getName() which returns the fully qualified class name, including packages, either do something like:
new ZipEntry(classFile.getName().replaceAll(@".", "/")
Or just new ZipEntry(filename);

**Comment by prupe** [comment]
Thanks for catching that.  How did you run across that?  Are you writing a custom mod?

**Comment by LexManos** [comment]
In short yes, Im looking for a good deployment method for a mod im creating.
And MCPatcher looks really good. I just need to learn how to understand the low level byte code stuff.
Any help/points would be appreciated :)

**Comment by prupe** [comment]
Wow, I didn't expect anyone to try using that so soon.  In the doc folder, there are some reference stuff and a link to the MCPatcher javadocs, which you can generate from the source by running "make javadoc".

I learned the bytecode stuff by trial and error, between looking at xau's original code and editing java source files while observing the changes in the Eclipse bytecode plugin.  The exceptions thrown by the JVM are surprisingly helpful when you generate bad bytecode.

**Comment by LexManos** [comment]
Ya im just starting the bytecode crap, so itll be a while before I get to where it can actually do stuff.
Though I already already got a big of the features done due to the raw replace file feature.

If this turns out to be as powerful as I think it is, then this will be an awesome solution, Just hard to learn at first.

Right now im just trying to figure out how to replace a specific classes's constructor.
Also, anything I should know about setting up intellij for mcpather/getting git to work?
Feel free to Email me at LexManos@gmail.com if you're free to talk.

**Comment by prupe** [comment]
Should be fixed now (beta2).  Let me know if you still have problems.
