### ISSUE TITLE
Use mipmaps for really high res texture packs

### ISSUE THREAD

**Issue by dagit** [pclewis/mcpatcher#32]
I wrote this on the forums, but I realize you may not read that so I'm putting it here:
I noticed that the really high res texture packs have kind of a weird look to them.  I was playing with texturing in a small opengl program I wrote and I noticed that with 256x256 textures, they looked dramatically better if I called gluBuild2DMipmaps when creating texture objects.  I would guess that anything over 32x32 would benefit but I didn't check.  I know that 128x128 and higher would benefit though.

I noticed that this page says to never use that function:
http://www.opengl.org/wiki/Common_Mistakes#gluBuild2DMipmaps

This post explains the pros/cons to gluBuild2DMipmaps vs. the newer stuff.  Since minecraft uses power of 2 textures and no shader stuff, I think that gluBuild2DMipmaps would be fine:
http://www.gamedev.net/topic/452780-gl_generate_mipmap-vs-glubuild2dmipmaps/

If you do use gluBuild2Mipmaps, it's pretty easy and you can find documentation for it here:
http://graphics.stanford.edu/courses/cs248-01/OpenGLHelpSession/code_example.html

It looks like this:
     // Create texture for cube; load marble texture from file and bind it
     pTextureImage = read_texture("marble.rgb", &width, &height, &nComponents);
     glBindTexture(GL_TEXTURE_2D, TEXTURE_ID_CUBE);
     gluBuild2DMipmaps(GL_TEXTURE_2D,     // texture to specify
                       GL_RGBA,           // internal texture storage format
                       width,             // texture width
                       height,            // texture height
                       GL_RGBA,           // pixel format
                       GL_UNSIGNED_BYTE,    // color component format
                       pTextureImage);    // pointer to texture image
     glTexParameterf (GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
     glTexParameterf (GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER,
                      GL_LINEAR_MIPMAP_LINEAR);

Just look at the InitGraphics function.

If you want to follow the advice of that "common mistakes" wiki, there are examples of the other stuff:

http://www.opengl.org/sdk/docs/man3/xhtml/glGenerateMipmap.xml
http://www.khronos.org/opengles/sdk/1.1/docs/man/glTexParameter.xml

Is there any chance this modification could be made to minecraft when using the HD texture patcher?  I think it would dramatically improve the really high-end HD texture packs.

Thanks for making this mod!

**Comment by prupe** [comment]
The new patcher is designed to be extensible, so I'd definitely like to add more features like this.

How would this work with animated textures?  The game implements these by simply drawing over parts of terrain.png and items.png in memory every frame.  Now I don't know much about OpenGL, but I'd assume the mipmaps would only get generated once and regenerating them every fram would be too expensive.  Is there an easy way around this?

**Comment by dagit** [comment]
I thought about this for a while, but I haven't tested it.  Here are my thoughts:
- At first, let's just try it without using mipmaps for animated textures
- If that ends up looking bad, we could try pre-computing all the animation stages and storing the textures
- Stand in front of a lot of animated textures and see what it does to the performance if we recompute mipmaps every frame.

Does that sound like a good plan?

**Comment by prupe** [comment]
Ok, I did some experiments.  There are a bunch of graphical artifacts: lines around each block and letter; clouds look strange, but it does improve the look of things far away.

As expected, gluBuild2DMipmaps does not update animated textures.  When you are more than a few feet away, animated textures fade into whatever was in terrain.png when it was first loaded.

GL_GENERATE_MIPMAP isn't defined, but I found its integer value 33169 and used it directly.  Same graphical artifacts, but it does update animated textures.  The performance penalty is huge though: Noticeably slower at 16x, and at 256x, runs at about 0.2fps.

glGenerateMipmap doesn't appear to be defined in lwjgl.jar at all.  I guess it's too new.

Do you have mcp set up, and do you think you can play around with it some?  I can tell you exactly where to add the extra GL calls:  RenderEngine.java, method setupTexture, right after the line "imageData.position(0).limit(abyte0.length);"

**Comment by dagit** [comment]
That's too bad.

I doubt I'll setup mcp.  I don't have a java development environment configured on any of my machines and from the sounds of your experiments it's going to be a pain to get it to work correctly with good performance.

Thanks for trying it out!  I appreciate that.  Now I'll stop telling people that MC should use mipmaps :)
