### ISSUE TITLE
Better Grass & Modloader v3 compatibility

### ISSUE THREAD

**Issue by Terak** [pclewis/mcpatcher#33]
Hello ive noticed that the cn.class file used by better grass conflicts with the modloader cn.class file.

When you patch a clean minecraft jar then copy over modloader it causes the side grass colour to become gray. The orginal better grass mod had a compatiblity patch for modloader what is not compatible with mcpatcher version of better grass. So it required a compatibility patch to work with Risugami Modloader

Image of the issue
http://dl.dropbox.com/u/26222524/Minecraft/Images/Screenshots/2011-05-03_17.24.56.png

you can find modloader here 
http://www.minecraftforum.net/viewtopic.php?f=25&t=80246

**Comment by prupe** [comment]
Does running the patcher after installing ModLoader work?  It seems to work ok for me, but people on the forum have said the game crashes.

**Comment by Terak** [comment]
Ive just tried it with a fresh jar like you said and it is the first time its worked in the past its just crashed for me even with a clean jar file as well as deleting the whole minecraft folder in %appdata%.
