### ISSUE TITLE
Conflict file overwrites happen in different orders for base vs nonbase classes

### ISSUE THREAD

**Issue by BloodyRain2k** [pclewis/mcpatcher#34]
When files conflict, 2.1.0_02 will use the last appearing base class file in the active mods list but the first non base class files.

For better explanation: Modloader MP (MLMP) overwrites a non base class file of Modloader: MLProp.class
So you would expect to place MLMP below Modloader so it would overwrite Modloaders version of MLProp.class
But it does in fact the opposite: it adds Modloaders MLProp.class and then refuses to add MLMP's version.
So you have to place MLMP over Modloader so it will use MLMP's version and refuse to overwrite that with Modloaders.

For base class files it works the other way round which is as I guess the intended and expected behavior. That's why you have to place the Forge API below the Modloaders as it overwrites base class files from both.

But if a mod now would have to overwrite a base class and a non base class you couldn't properly place it due to the different overwrite orders.

And no, removing the conflict files from either mods for the patching process isn't a solution. If you end up trying a new combination you'll forget that have removed them so they end up missing and you'll be chasing a problem that doesn't have to be there.

**Comment by prupe** [comment]
Thanks for catching this!  I've checked in a fix.  I expect that the 1.8 update will break the patcher anyway, so I'll wait until then to make a new release.
