### ISSUE TITLE
2.1.2 jar no good

### ISSUE THREAD

**Issue by mrgoo** [pclewis/mcpatcher#38]
When I attempt to download 2.1.2 direct from get hub I get the following error

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>CE66653D4FB77CEA</RequestId>
<HostId>
UwyYXkVwX9uEtTAhFs5VaQDOgmFwqyui9w26yFcYundD2Axhtrtk/JBXN0uzclk/
</HostId>
</Error>

All the other download links are fine but this file there is a problem with the link.

I am a java programmer myself and use github fir my work, but there seen this issue  you might need to re upload the file.

thanks

**Comment by prupe** [comment]
I have this problem every time I upload to github.  It hangs at "starting upload" and never makes any progress.  Usually I can delete the file and retry and get it to work, but this time it failed several times in a row until I just gave up.  Maybe I'll have better luck with the next release.  In the meantime you can use the adfly link on the forums.
