### ISSUE TITLE
Black Screen After Using MCPatcher 2.3.2 and Previous Version

### ISSUE THREAD

**Issue by Bri619123** [pclewis/mcpatcher#44]
I just recently updated to 1.1 and had to update to the newest version of MC patcher to use HD texture packs. Whenever I patch with MCpatcher I get a black screen right after login without using any mods except the ones provided by mcpatcher. I have deleted my minecraft folder and reinstalled 1.1. I have uninstalled and reinstalled the newest version of Java. I have tried using both the .exe and .jar both with the same result. If I patch just the HD Textures without any of the other mods the game will load just fine, but after I select a HD texture pack all of the text is unreadable. If I patch just the HD fonts the game works fine, but then I obviously wont have HD Textures. If I patch BOTH, the game is un-runable and I get the black screen after login. HELP! Thanks!

**Comment by prupe** [comment]
A black screen isn't much to go on.  Is there a stack trace in the MCPatcher log window when you click Test Minecraft?
