### ISSUE TITLE
Feature Request: @AlreadyPatched Java Annotation

### ISSUE THREAD

**Issue by thvortex** [pclewis/mcpatcher#51]
I have a feature request which would be useful to other mod authors who are trying to make their mods more compatible with MCPatcher. My [BetterFonts](https://github.com/thvortex/BetterFonts) mod modified FontRenderer which is also used by HD Textures and HD Fonts. I've tried to make my code more compatible by manually including the initialize() method that MCPatcher inserts, and this works when my mod is manually copied to minecraft.jar after running MCPatcher. However, when someone tried to install my mod through MCPatcher itself, they get a [DuplicateMemberException](http://www.minecraftforum.net/topic/1142084-131-betterfonts-truetypeopentype-font-support/page__st__100#entry17176052). So trying to fix one problem caused another.

The idea behind this @AlreadyPatched annotation is that MCPatcher would either avoid patching any methods/fields with this annotation, or maybe would ignore any exceptions thrown by Javassist when applying that particular patch. Ideally the user could apply patches before or after installing my own mod (manually or with MCPatcher) and it would all "just work".

**Comment by prupe** [comment]
I went with something simpler.  MCPatcher simply ignores the DuplicateMemberException by default now.  If another mod adds a method with the same name and signature but does something totally different, then it could cause a problem, but that doesn't seem likely.

Will this work for you?

**Comment by thvortex** [comment]
That will definitely help. Thanks. I've also noticed that in some cases MCPatcher will replace a method completely like FontRenderer.getStringWidth (using MCP deobfuscation names). I guess that would still be a problem depending on what order the mod is installed.
