### ISSUE TITLE
CTM not working in texture pack folders (with fix!)

### ISSUE THREAD

**Issue by MWisBest** [pclewis/mcpatcher#54]
https://github.com/pclewis/mcpatcher/blob/master/newcode/src/com/pclewis/mcpatcher/mod/CTMUtils.java#L66

That line should be replaced with "registerOverride(TileOverride.create(s.replace(".properties", "").replace("\\", "/"), null));" and it will fix CTM not working with texture pack folders.

**Comment by prupe** [comment]
This should be working in the latest MCPatcher.  If not, please re-open and I'll take another look.
