### ISSUE TITLE
Backup is loaded instead patched version

### ISSUE THREAD

**Issue by 13ilya-old** [pclewis/mcpatcher#58]
After patch mcpather make in bin directory backup (minecraft-1.4.2.jar), backup is loaded instead patched version, and if it is not removed, the original game is loaded without animated textures of water and lava.
After manually removing the backup (minecraft-1.4.2.jar), patched the game to load properly.
## !/bin/bash

java -cp './bin/*' -Xms1024M -Xmx1024M -Djava.library.path='./bin/natives/' net.minecraft.client.Minecraft ILYA

**Comment by Freso** [comment]
Can you do an `ls -Al ~/.minecraft/bin/` when MC runs from the backup instead of the patched version? Did you change any settings? What happens when you run `java -Xms1024M -Xmx1024M -cp /usr/share/minecraft/minecraft.jar net.minecraft.LauncherFrame` instead of that command you're trying to run? (With "/usr/share/minecraft/" being replaced with the path to your launcher minecraft.jar, not the ~/.minecraft/bin one.)

What happens if you use a proper shebang line (`#!/bin/bash` instead of `##!/bin/bash`)?

Also, what's your $LD_LIBRARY_PATH?

**Comment by 13ilya-old** [comment]
ilya@ILYA:~/.minecraft> ls -Al ~/.minecraft/bin/
итого 10972
-rw-r--r-- 1 ilya ilya  214859 окт.   9 01:43 jinput.jar
-rw-r--r-- 1 ilya ilya  941293 окт.   9 01:43 lwjgl.jar
-rw-r--r-- 1 ilya ilya  173342 окт.   9 01:43 lwjgl_util.jar
-rw-r--r-- 1 ilya ilya 4928385 окт.  25 19:14 minecraft-1.4.2.jar
-rw-r--r-- 1 ilya ilya 4959224 окт.  25 19:18 minecraft.jar
drwxr-xr-x 2 ilya ilya    4096 окт.   9 01:43 natives

Settings
http://ilya.pp.ua/mc1.png
http://ilya.pp.ua/mc2.png

Screenshot
http://ilya.pp.ua/mc3.png

Minecraft "installed" in ~/.minecraft/ directory /usr/share/minecraft/ not exist
ilya@ILYA:~/.minecraft> java -Xms1024M -Xmx1024M -cp /usr/share/minecraft/minecraft.jar net.minecraft.LauncherFrame
Error: Could not find or load main class net.minecraft.LauncherFrame

> What happens if you use a proper shebang line (#!/bin/bash instead of ##!/bin/bash)?

Nothing has changed.

$LD_LIBRARY_PATH
/usr/lib64

**Comment by Freso** [comment]
What happens if you use "Test Minecraft"?

Also, your Minecraft launcher obviously isn't in ~/.minecraft - and like I said, replace `/usr/share/minecraft/minecraft.jar` with the proper path to the launcher jar. I can't tell you where that is without knowing how you've installed Minecraft. (I installed it using the AUR package for ArchLinux, but chances are you're not using ArchLinux.)

Also, your $LD_LIBRARY_PATH seems to be a bit short. http://sprunge.us/JeJU is what I have in `/usr/bin/minecraft` on my system.

**Comment by 13ilya-old** [comment]
I copied from ~/.minecraft in /usr/share/minecraft
Pointed the way to mcpatcher to /usr/share/minecraft/bin/minecraft.jar

How me look $LD_LIBRARY_PATH ?

Nothing has changed.

Install it so:
1 Download from this torrent http://rutracker.org/forum/viewtopic.php?t=4163228

bin · 7.14 MB
    jinput.jar 209.82 KB (214859)
    lwjgl.jar 919.23 KB (941293)
    lwjgl_util.jar 169.27 KB (173342)
    minecraft.jar 4.37 MB (4586019)
    natives · 1.50 MB
        libjinput-linux.so 13.5 KB (13824)
        libjinput-linux64.so 14.17 KB (14512)
        liblwjgl.so 365.96 KB (374744)
        liblwjgl64.so 426.92 KB (437176)
        libopenal.so 344.87 KB (353148)
        libopenal64.so 374.86 KB (383860)
start.sh 153 B (153)
update.sh 89 B (89)

Move it to ~/.minecraft and wrote his runner and the updater.

#!/bin/bash
java-cp './bin/*'-Xms1024M-Xmx1024M-Djava.library.path='./bin/natives/' net.minecraft.client.Minecraft ILYA

#!/bin/bash
cd./bin && rm-f minecraft.jar && wget http://s3.amazonaws.com/MinecraftDownload/minecraft.jar

Then download the texture packs
http://www.planetminecraft.com/texture_pack/ovos-rustic-pack/
and
http://www.planetminecraft.com/texture_pack/64x64-1112wo7b-ovos-rustic--continuation--v24/

and move them to ~/.minecraft/texturepacks/

3 Then I learned that the texture to patch with mcpatcher and I downloaded it from this site, and have moved to ~/.minecraft/ from it and run.

I do not understand what does this have to do with the fact that mcpatcher puts his backup (original) in the same folder in which the patched version, and the original is loaded BEFORE patched version and patched version is ignored for?
The original can be obtained by a second by command
wget http://s3.amazonaws.com/MinecraftDownload/minecraft.jar
and do not need to be stored.
And if you want to keep and then or at another location, or to another extension, or the name that will be preloaded AFTER patched version, and would be even better that he did not do, even if optional checkbox.

**Comment by Freso** [comment]
I'm going to repeat this with some emphasis added: "(With "/usr/share/minecraft/" being replaced with the path to your launcher minecraft.jar, **not the ~/.minecraft/bin one.**)"

The original bin/minecraft.jar is stored/backed up as mcpatcher is using that to patch against every time you run the patcher. MCPatcher can't patch an already patched minecraft.jar. Also, it's illegal to download minecraft.jar from anywhere else than Mojang's server. What you described above doesn't sound anything close to legal, so I'm going to bail out of this one. Good luck.

**Comment by prupe** [comment]
IlyaIndigo,
I'm not going to support someone using a pirated copy of the game.  Your bash script is broken.  Figure it out and fix it yourself.
